# Generated by Django 4.2.3 on 2023-11-17 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_niche_remove_product_vendor_delete_vendor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorderitems",
            options={"verbose_name_plural": "Cart Items"},
        ),
    ]
