# Generated by Django 4.2.3 on 2023-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_cartorderitems_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=9999999999
            ),
        ),
    ]
